CREATE DATABASE Aula_01 CHARSET = latin1 COLLATE latin1_general_cs;

CREATE TABLE CONVENIO(
COD_CONVENIO INT NOT NULL PRIMARY KEY,
NOM_CONVENIO VARCHAR (30)
);	  	

CREATE TABLE EXAME(
COD_EXAME INT NOT NULL PRIMARY KEY,
DES_EXAME VARCHAR (50)
);

CREATE TABLE ESPECIALIDADE(
COD_ESPECIALIDADE INT NOT NULL PRIMARY KEY,
DEN_ESPECIALIDADE VARCHAR (50)
);

CREATE TABLE MEDICO(
NUM_CPF_MEDICO INT NOT NULL PRIMARY KEY,
NOM_MEDICO VARCHAR (60),
NUM_INS_CRM INT NOT NULL,
HOR_INI_ATDMTO TIMESTAMP ('03/09/2018')
HOR_FIM_ATDMTO TIMESTAMP ('04/09/2018')
);

CREATE TABLE PACIENTE(
NUM_CPF_PACIENTE INT NOT NULL PRIMARY KEY,
NOM_PACIENTE VARCHAR (60), 
NUM_TELEFONE VARCHAR (20),
FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE
);

CREATE TABLE ATUACAO(
FOREIGN KEY (NUM_CPF_MEDICO) REFERENCES MEDICO,
FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE,
PRIMARY KEY (NUM_CPF_MEDICO, COD_ESPECIALIDADE)
);

CREATE TABLE CONSULTA(
NUM_CONSULTA INT PRIMARY KEY,
DAT_CONSULTA DATE ('07/09/2018'),
HOR_CONSULTA TIMESTAMP ('07/09/2018'),
FOREIGN KEY (NUM_CPF_MEDICO) REFERENCES MEDICO,
FOREIGN KEY (NUM_CPF_PACIENTE) REFERENCES PACIENTE,
FOREIGN KEY (COD_CONVENIO) REFERENCES CONVENIO
);

CREATE TABLE REQUISICAO(
FOREIGN KEY (NUM_CONSULTA) REFERENCES CONSULTA,
FOREIGN KEY (COD_EXAME) REFERENCES EXAME
);

CREATE TABLE PRESCRICAO(
NUM_PRESCRICAO INT NOT NULL,
DES_PRESCRICAO TEXT NOT NULL
)